### ISSUE TITLE
Not compatible with new M1 silicon macOS?

### ISSUE THREAD

**Issue by kamusis** [tomy0000000/Coinc#15]
Laptop: Macbook Pro with M1 silicon
Alfred: 4.2.1 Universal version
The very first time launch after installation looks good, from the second launch, always got error as below.
![image](https://user-images.githubusercontent.com/1849506/100521888-f1df0d00-31e9-11eb-81fb-1f5e86cd733e.png)

Here is the logs after turning on debug mode.
```
[02:39:15.696] Logging Started...
[02:39:30.994] Coinc[Script Filter] Queuing argument '(null)'
[02:39:31.367] Coinc[Script Filter] Script with argv '(null)' finished
[02:39:31.368] ERROR: Coinc[Script Filter] Code 1: .
02:39:31 workflow.py:2061 DEBUG    ---------- Coinc (1.3.0) ----------
02:39:31 workflow.py:1468 DEBUG    reading settings from /Users/kamus/Library/Application Support/Alfred/Workflow Data/tech.tomy.coinc/settings.json
02:39:31 workflow.py:2338 INFO     checking for update ...
02:39:31 background.py:230 DEBUG    [__workflow_update_check] command cached: /Users/kamus/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/tech.tomy.coinc/__workflow_update_check.argcache
02:39:31 background.py:234 DEBUG    [__workflow_update_check] passing job to background runner: [u'/usr/bin/python', '/Users/kamus/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.81C8A43D-39ED-49C5-B6DE-956EBCFBAE0C/workflow/background.pyc', u'__workflow_update_check']
.
02:39:31 workflow.py:2061 DEBUG    ---------- Coinc (1.3.0) ----------
02:39:31 background.py:240 DEBUG    [__workflow_update_check] background job started
02:39:31 workflow.py:2080 ERROR    [Errno 66] Directory not empty
Traceback (most recent call last):
  File "/Users/kamus/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.81C8A43D-39ED-49C5-B6DE-956EBCFBAE0C/workflow/workflow.py", line 2073, in run
    func(self)
  File "main.py", line 12, in main
    if coinc.utils.manual_update_patch(workflow):
  File "/Users/kamus/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.81C8A43D-39ED-49C5-B6DE-956EBCFBAE0C/coinc/utils.py", line 62, in manual_update_patch
    os.rename(old_path, new_path)
OSError: [Errno 66] Directory not empty
02:39:31 workflow.py:2082 INFO     for assistance, see: https://git.io/JfjXg
02:39:31 workflow.py:2103 DEBUG    ---------- finished in 0.166s ----------
[02:39:31.377] Coinc[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "[Errno 66] Directory not empty",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Coinc'"
    }
  ]
}
```

**Comment by kamusis** [comment]
After delete Workflow Data/tech.tomy.coon, everything is good.
